### ISSUE TITLE
client.modify() assertion on empty string 

### ISSUE THREAD

**Issue by 6Beaufort** [mcavage/node-ldapjs#105]
Hello Marc,

your library is really great but I think I found a bug in client.modify(). I use the change object (see below). If title is an empty string, I get the assertion as shown below. With the following workaround (give it at least a blank instead of an empty string) it runs.

TESTED WITH
latest node.js version 0.89 and ldap.js version 0.57

CODE LEADING TO ASSERTION (when entry.title is an empty string)
var change = new ldap.Change({
             operation: 'replace',
             modification: {
                        title: entry.title
             }
 });

CODE WITH WORKAROUND
var change = new ldap.Change({
             operation: 'replace',
             modification: {
                        title: (entry.title == '') ? ' ' : entry.title,   // bug workaround in LDAPJS
             }
 });

ASSERTION WITHOUT THIS WORKAROUND
assert.js:334
assert.ifError = function(err) { if (err) {throw err;}};
                                                 ^
InvalidAttributeSyntaxError: title: value #0 invalid per syntax
    at messageCallback (/Library/WebServer/Documents/stormtest/node_modules/ldapjs/lib/client/client.js:847:40)
    at Parser.onMessage (/Library/WebServer/Documents/stormtest/node_modules/ldapjs/lib/client/client.js:191:12)
    at Parser.EventEmitter.emit (events.js:88:17)
    at Parser.write (/Library/WebServer/Documents/stormtest/node_modules/ldapjs/lib/messages/parser.js:108:8)
    at Socket.onData (/Library/WebServer/Documents/stormtest/node_modules/ldapjs/lib/client/client.js:152:24)
    at Socket.EventEmitter.emit (events.js:88:17)
    at TCP.onread (net.js:396:14)

**Comment by malek0512** [comment]
Hello,

I have the exact same issue, with 0.7.1 version of Ldapjs.

**What I do**
```javascript
var change = new ldap.Change({
     operation: 'replace',
     modification: {employeeNumber: ''}
});
```
**The error**
{ dn: '',
     code: 21,
     name: 'InvalidAttributeSyntaxError',
     message: 'employeeNumber: value #0 invalid per syntax\n' }

I have managed to solve this by inserting a space instead of an empty string.
