### ISSUE TITLE
Connection pool : Cannot call method 'unbind' of undefined

### ISSUE THREAD

**Issue by cvillemure** [mcavage/node-ldapjs#129]
Is it a misconfiguration on my side or is the code missing a sanity check?
## My config : 

``` javascript
var ldap_client.IMS = ldap.createClient({
   url : 'ldap://' + ldapConfig.HOSTNAME + ':' + ldapConfig.PORT,
   timeout : 2000, //Each operation have 2 seconds to complete
   connectTimeout : 10000, //Each tentative to connect timeout after 10 seconds
   maxConnections : 100 //Connection pool of 100 connections
});
```
## The error : 

[2013-04-18 07:50:18.080] [ERROR] app - Uncaught exception : 
[2013-04-18 07:50:18.129] [ERROR] app - [TypeError: Cannot call method 'unbind' of undefined]
TypeError: Cannot call method 'unbind' of undefined
    at Pool.destroy (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\lib\client\pool.js:93:14)
    at Pool._kill (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\node_modules\pooling\lib\pool.js:549:22)
    at createCallback (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\node_modules\pooling\lib\pool.js:406:38)
    at Client.onConnect (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\lib\client\pool.js:56:18)
    at Client.g (events.js:192:14)
    at Client.EventEmitter.emit (events.js:96:17)
    at Socket.onConnect (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\lib\client\client.js:721:10)
    at Socket.g (events.js:192:14)
    at Socket.EventEmitter.emit (events.js:93:17)
    at Object.afterConnect [as oncomplete](net.js:752:10)
## Another error before unbind error : 

[2013-04-18 08:37:02.519] [ERROR] ldap.LDAPUtil - { message: 'pool is shutting down',
  name: 'PoolShuttingDownError' }
PoolShuttingDownError: pool is shutting down
    at Pool.acquire (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\node_modules\pooling\lib\pool.js:204:26)
    at ClientPool.search (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\lib\client\pool.js:193:20)
    at C:\Borealis\4_0\IMS\server\IMS\ldap\LDAPUtil.js:31:15
    at ClientPool.bind (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\lib\client\pool.js:261:16)
    at _done (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\lib\client\client.js:771:12)
    at messageCallback (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\lib\client\client.js:849:16)
    at Parser.onMessage (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\lib\client\client.js:191:12)
    at Parser.EventEmitter.emit (events.js:96:17)
    at Parser.write (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\lib\messages\parser.js:108:8)
    at Socket.onData (C:\Borealis\4_0\IMS\server\node_modules\ldapjs\lib\client\client.js:152:24)

**Comment by ORESoftware** [comment]
+ 1 Agree that it would be nice to have the documentation talk about connection pooling with LDAP
