### ISSUE TITLE
LDAP MATCHING RULE BIT AND

### ISSUE THREAD

**Issue by MaximeHeckel** [mcavage/node-ldapjs#200]
Hi,

I have to use the LDAP_MATCHING_RULE_BIT_AND in order to list all non disable account by using the following filter : 

!userAccountControl:1.2.840.113556.1.4.803:=2

But it doesn't work.
Can we use such rule with LDAPJS ?
I use the [node-activedirectory](https://github.com/gheeres/node-activedirectory) plugin, which uses LDAPJS, and I didn't manage to make filters work properly.

Thank you in advance for your help

**Comment by rprieto** [comment]
I have the same issue trying to use `LDAP_MATCHING_RULE_BIT_AND`. This is a common query for Active Directory, where the user status is stored in a bit field called `userAccountControl` (see https://support.microsoft.com/en-us/kb/269181 or http://jackstromberg.com/2013/01/useraccountcontrol-attributeflag-values/).

I also agree the corresponding valid LDAP query is `!(userAccountControl:1.2.840.113556.1.4.803:=2)`, which works well when using `ldapsearch`.

However when trying to use this query on LDAPJS, for example as part of `req.filter.matches(user.attributes)`, I get the following error:

```
OperationsError: ext match implementation missing
  at messageCallback (node_modules/ldapjs/lib/client/client.js:1419:45)
  at Parser.onMessage (node_modules/ldapjs/lib/client/client.js:1089:14)
  at emitOne (events.js:96:13)
  at Parser.emit (events.js:188:7)
  at Parser.write (node_modules/ldapjs/lib/messages/parser.js:111:8)
  at Socket.onData (node_modules/ldapjs/lib/client/client.js:1076:22)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at Socket.Readable.push (_stream_readable.js:134:10)
```

Can you think of anything obviously wrong, or is it simply that bit-matching rules aren't supported yet?

**Comment by andreimirt** [comment]
I am having the same issue when trying to set up gitlab-ce authentication with ldapjs. Is this entirely not supported? Or is there a workaround?
I am a newbie about ldap, but my log looks like this:

```
INFO: 2023-04-07T20:00:04.236Z:  server.js server.search Search for => DB: uid=some.user,cn=users,dc=mydomain,dc=com; Scope: base; Filter: (userAccountControl:1.2.840.113556.1.4.803:=2); Attributes: dn;
INFO: 2023-04-07T20:00:04.237Z:  server.js server.search searchableEntries NOT modified 17
ERROR: 2023-04-07T20:00:04.238Z:  server.js server.search Error: ext match implementation missing
    at ExtensibleFilter.matches (/app/node_modules/ldap-filter/lib/ext_filter.js:81:9)
    at Server.<anonymous> (/app/server.js:312:32)
    at messageIIFE (/app/node_modules/ldapjs/lib/server.js:407:63)
    at Server.authorize (/app/server.js:116:12)
    at messageIIFE (/app/node_modules/ldapjs/lib/server.js:407:63)
    at Parser.<anonymous> (/app/node_modules/ldapjs/lib/server.js:430:8)
    at Parser.emit (node:events:513:28)
    at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:107:8)
    at Socket.<anonymous> (/app/node_modules/ldapjs/lib/server.js:449:19)
    at Socket.emit (node:events:513:28)
```

**Comment by jsumners** [comment]
This is an old issue. If you have a current problem, please open a new issue.
