### ISSUE TITLE
DNS errors not handled

### ISSUE THREAD

**Issue by tstiemerling** [mcavage/node-ldapjs#234]
In version 0.7.1.

If I specify an invalid DNS address in client an exception results, rather than clean error callback:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete](dns.js:124:16)

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
