### ISSUE TITLE
TypeError: Cannot call method 'on' of undefined

### ISSUE THREAD

**Issue by littlejo** [mcavage/node-ldapjs#235]
Hello,

I have a trouble with ldapjs (ldap search method). I'm using ldapjs with sharelatex:
https://github.com/heukirne/web-sharelatex/commit/fd0a76d366020994a49723881b4d656542e660ee

```
"ldapjs": "0.7.1",
```

When i launch sharelatex server, there is no problem: i can authenticated with ldap client.

But with a small time of inactivity, i have some trouble:
[2014-10-12T08:01:21.185Z] ERROR: web-sharelatex/16490 on latex: error passed to top level next middlewear (url=/register, method=POST)
    TypeError: Cannot call method 'on' of undefined
      at /home/sharelatex/web/app/js/Features/Security/LdapAuth.js:33:24
      at Client._send (/home/sharelatex/web/node_modules/ldapjs/lib/client/client.js:920:12)
      at Client.search (/home/sharelatex/web/node_modules/ldapjs/lib/client/client.js:678:15)
      at Object.module.exports.authDN (/home/sharelatex/web/app/js/Features/Security/LdapAuth.js:32:26)
      at Object.module.exports.registerNewUser (/home/sharelatex/web/app/js/Features/User/UserRegistrationHandler.js:88:23)
      at module.exports.register (/home/sharelatex/web/app/js/Features/User/UserController.js:153:38)
      at callbacks (/home/sharelatex/web/node_modules/express/lib/router/index.js:161:37)
      at param (/home/sharelatex/web/node_modules/express/lib/router/index.js:135:11)
      at pass (/home/sharelatex/web/node_modules/express/lib/router/index.js:142:5)
      at Router._dispatch (/home/sharelatex/web/node_modules/express/lib/router/index.js:170:5)
      at Object.router (/home/sharelatex/web/node_modules/express/lib/router/index.js:33:10)
      at next (/home/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/home/sharelatex/web/app/js/infrastructure/Server.js:151:14)
      at next (/home/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.app.use.res.render.title [as handle](/home/sharelatex/web/app/js/infrastructure/Server.js:141:12)
      at next (/home/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.module.exports [as handle](/home/sharelatex/web/app/js/infrastructure/OldAssetProxy.js:21:14)
      at next (/home/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.module.exports [as handle](/home/sharelatex/web/app/js/infrastructure/RedirectManager.js:23:14)
      at next (/home/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/home/sharelatex/web/node_modules/metrics-sharelatex/http.coffee:30:3)
      at next (/home/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/home/sharelatex/web/app/js/infrastructure/ExpressLocals.js:187:14)
      at next (/home/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/home/sharelatex/web/app/js/infrastructure/ExpressLocals.js:180:14)
      at next (/home/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at /home/sharelatex/web/app/js/infrastructure/ExpressLocals.js:170:16
      at Object.module.exports.SystemMessageManager.getMessages (/home/sharelatex/web/app/js/Features/SystemMessages/SystemMessageManager.js:12:16)
      at Object.handle (/home/sharelatex/web/app/js/infrastructure/ExpressLocals.js:165:35)
      at next (/home/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/home/sharelatex/web/app/js/infrastructure/ExpressLocals.js:162:14)
      at next (/home/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/home/sharelatex/web/app/js/infrastructure/ExpressLocals.js:157:14)

I can't authenticate anymore after that. I have to relaunch sharelatex server to be able to authenticate.

I would like to know if it's a bug of ldapjs if you are a solution to my problem.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
