### ISSUE TITLE
ConstraintViolationError: Exceed password retry limit. Account locked.

### ISSUE THREAD

**Issue by jjg77** [mcavage/node-ldapjs#248]
Using passport-ldapauth module and getting this error when trying to login using a locked account.  The trace below points to ldapjs client.  Any ideas?

ConstraintViolationError: Exceed password retry limit. Account locked.
   at messageCallback (C:\Users\jg63717\projects\raap\node_modules\passport-ldapauth\node_modules\ldapauth-fork\node_modules\ldapjs\lib\client\client.js:867:40)
   at Parser.onMessage (C:\Users\jg63717\projects\raap\node_modules\passport-ldapauth\node_modules\ldapauth-fork\node_modules\ldapjs\lib\client\client.js:199:12)
   at Parser.emit (events.js:95:17)
   at Parser.write (C:\Users\jg63717\projects\raap\node_modules\passport-ldapauth\node_modules\ldapauth-fork\node_modules\ldapjs\lib\messages\parser.js:105:8)
   at CleartextStream.onData (C:\Users\jg63717\projects\raap\node_modules\passport-ldapauth\node_modules\ldapauth-fork\node_modules\ldapjs\lib\client\client.js:155:24)
   at CleartextStream.emit (events.js:95:17)
   at CleartextStream.<anonymous> (_stream_readable.js:764:14)
   at CleartextStream.emit (events.js:92:17)
   at emitReadable_ (_stream_readable.js:426:10)
   at _stream_readable.js:419:7

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
