### ISSUE TITLE
Issue while connecting to ActiveDirectory server (from windows)

### ISSUE THREAD

**Issue by davidrapin** [mcavage/node-ldapjs#262]
```
stack:
 ReferralError: 0000202B: RefErr: DSID-031006E0, data 0, 1 access points
 ref 1: 'bridgewater'
 \u0000

 at messageCallback (node_modules\\ldapjs\\lib\\client\\client.js:867:40)
 at Parser.onMessage (node_modules\\ldapjs\\lib\\client\\client.js:199:12)
 at Parser.emit (events.js:95:17)
 at Parser.write (node_modules\\ldapjs\\lib\\messages\\parser.js:105:8)
 at Socket.onData (node_modules\\ldapjs\\lib\\client\\client.js:155:24)
 at Socket.emit (events.js:95:17)
 at Socket.<anonymous> (_stream_readable.js:764:14)
 at Socket.emit (events.js:92:17)
 at emitReadable_ (_stream_readable.js:426:10)
 at emitReadable (_stream_readable.js:422:5)
 at readableAddChunk (_stream_readable.js:165:9)
 at Socket.Readable.push (_stream_readable.js:127:10)
 at TCP.onread (net.js:528:21)
```

**Comment by randomsock** [comment]
David, don't know if it helps you too, but I got round this by connecting to our Global Catalog instead - port 3268 but otherwise everything is the same - so it doesn't have to refer on sub domains.  Is this a possibility in your setup?

**Comment by pfmooney** [comment]
Potentially related to #263

**Comment by davidrapin** [comment]
Thanks. I notice that I didn't get into much details while reporting this:
 - apparently, binding to the LDAP server worked, and this error was triggered while performing a search. 
 - the `bridgewater` keyword is actually the base DN.
 - the URL of the LDAP server as `ldap://BW-AD-PD1:389`
 - I was subscribed to the `error` events of my client but this error didn't trigger my listener

@randomsock I will try and discuss this with the customer that experienced this, as this did not happen to me directly. Thank you for the hint!

**Comment by davidrapin** [comment]
@pfmooney Any details on the reason behind closing this issue?

**Comment by pfmooney** [comment]
Since there had long since been a lull in activity after you mentioned consulting the customer, I assumed the issue had passed.  If you're encountering this condition during a search, I would recommend ensuring that you're subscribing to the `error` event on the response emitter passed to the search callback.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
