### ISSUE TITLE
Cannot handle ReferralError

### ISSUE THREAD

**Issue by randomsock** [mcavage/node-ldapjs#263]
Using the client `search`, I'm getting the following error reported through the result `error` event:

	ReferralError: 0000202B: RefErr: DSID-0310063C, data 0, 1 access points
			ref 1: 'a.n.other.server'

		at messageCallback (.../ldapjs/lib/client/client.js:867:40)
		at Parser.onMessage (.../ldapjs/lib/client/client.js:199:12)
		at Parser.emit (events.js:95:17)
		at Parser.write (.../ldapjs/lib/messages/parser.js:105:8)
		at Socket.onData (.../ldapjs/lib/client/client.js:155:24)
		at Socket.emit (events.js:95:17)
		at Socket.<anonymous> (_stream_readable.js:765:14)
		at Socket.emit (events.js:92:17)
		at emitReadable_ (_stream_readable.js:427:10)
		at emitReadable (_stream_readable.js:423:5)
		at readableAddChunk (_stream_readable.js:166:9)
		at Socket.Readable.push (_stream_readable.js:128:10)
		at TCP.onread (net.js:529:21)

It's killing my searches, and subscribing to the `searchReference` event doesn't make any difference, it doesn't pick it up.

Apart from the fact there doesn't seem a way to handle this error, is there any way to tell it to ignore referrals altogether?

**Comment by randomsock** [comment]
Have worked around this locally by connecting to the corporate Global Catalog so it doesn't have to refer you to individual domain controllers.  However, it does need addressing because it's currently fatal when you don't have that option.

**Comment by pfmooney** [comment]
Are you subscribed to the `error` event on the emitter provided by the the search callback?
That should be the appropriate way to handle this.

**Comment by randomsock** [comment]
I am, yes, and that's where the error was being picked up above.

I've just tried again to see if I can simply log this and let the search complete with a kind of "no-one *here* by that name, try elsewhere...", but once the `error` has raised, the `end` doesn't (seems reasonable generally).

I thought that was how the `searchReference` might work, and maybe that's the problem here is not understanding what the `searchReference` is for, and what's the difference between that event and this error ...?

**Comment by randomsock** [comment]
Alternatively, if you think this is a viable enhancement, it would solve the problem for a vast majority of people if it did automatic referral chasing.

That's a tricky thing to get right 100% of cases because if you are referred to an(other) external directory then you won't necessarily have the credentials to do that (and if i remember correctly, Microsoft mitigated this by attempting with anonymous access, but that's far from ideal).

If a lot of use cases for this in the real world are in a corporate domain hierarchy then you should be able to re-use the same credentials to access other subdomain controllers, that would certainly work for us here and I guess would be common.

So even a fairly niaive approach of simply applying the same search options and credentials to the referred access point(s) could fix this for 80% people.

Thoughts?  I'm snowed under with client's work at the moment but I'll have a look myself if i get chance.

**Comment by pfmooney** [comment]
I'm inclined to leave referral chasing up to the API consumer at this point.  It is a task that's rather complicated and I would rather put those failure modes in the hands of the implementer instead of deciding within ldapjs.

That said, if you do come up with something, I'll be happy to review it.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
