### ISSUE TITLE
Bunyan.child is not a function

### ISSUE THREAD

**Issue by flyswatter** [mcavage/node-ldapjs#264]
I'm getting a strange error, that seems to come from Bunyan's logger not having a `child` method at some times.

```
/my-project/node_modules/ldapjs/lib/client/client.js:318
  this.log = options.log.child({clazz: 'Client'}, true);
                         ^
TypeError: undefined is not a function
    at new Client (/my-project/node_modules/ldapjs/lib/client/client.js:318:26)
    at new createClient (/my-project/node_modules/ldapjs/lib/client/index.js:54:12)
```

The thing that's *really* strange though, is that if I add a `console.log()` right before the line that's throwing (318), this error doesn't happen.

Any idea why that might happen?

Running node v0.12.2 off the master branch here.

**Comment by pfmooney** [comment]
Could you provide more info about the code hitting this issue?

**Comment by flyswatter** [comment]
I'd never seen the issue before, until I put a `node-ldapjs` lookup on an [ActionHeroJS](http://www.actionherojs.com) action controller, it might be related to that.

I'll try to isolate the problem better when I get a chance.

**Comment by pfmooney** [comment]
Please let me know if you find anything of note.

**Comment by leolabs** [comment]
I've just experienced this error in a project of mine. As this issue is closed, is there a fix for this yet?

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
