### ISSUE TITLE
Uncaught Exception thrown from connection pool if filter string invalid

### ISSUE THREAD

**Issue by randomsock** [mcavage/node-ldapjs#284]
Node.js v0.12.2
ldapjs v0.7.1

I may have missed something simple here but I've read through the API and tried a number of things.

We are generating filter strings for querying our AD with the ldapjs Client, and have (wrongly) ended up creating a term with no value, eg. `(cn=)`.  That particular cause is fixed at our end now, but the problem was that it threw an exception at the time the filter was parsed asynchronously in the connection pool, and that went uncaught:

	/home/random/dev/adfoo/node_modules/ldapjs/lib/filters/index.js:206
		  throw new Error(expr + ' is invalid');
				^
	Error: cn= is invalid
		at _buildFilterTree (/home/random/dev/adfoo/node_modules/ldapjs/lib/filters/index.js:206:13)
		at _buildFilterTree (/home/random/dev/adfoo/node_modules/ldapjs/lib/filters/index.js:164:28)
		at _parseString (/home/random/dev/adfoo/node_modules/ldapjs/lib/filters/index.js:417:17)
		at Object.module.exports.parseString (/home/random/dev/adfoo/node_modules/ldapjs/lib/filters/index.js:547:12)
		at Client.search (/home/random/dev/adfoo/node_modules/ldapjs/lib/client/client.js:640:30)
		at onAcquire (/home/random/dev/adfoo/node_modules/ldapjs/lib/client/pool.js:209:19)
		at f (/home/random/dev/adfoo/node_modules/ldapjs/node_modules/pooling/node_modules/once/once.js:16:25)
		at onCreatedClient (/home/random/dev/adfoo/node_modules/ldapjs/node_modules/pooling/lib/pool.js:268:17)
		at createCallback (/home/random/dev/adfoo/node_modules/ldapjs/node_modules/pooling/lib/pool.js:439:17)
		at bindCallback (/home/random/dev/adfoo/node_modules/ldapjs/lib/client/pool.js:71:18)

So the general problem is that user-sourced parameter errors are fatal.

I haven't tried this yet, but as a workaround I guess we could pre-validate it with `parseFilter()`, although that would mean parsing it twice in all, and the question remains what other errors may not be thrown until then.

**Comment by pfmooney** [comment]
Pre-validation wouldn't be a bad idea if you're allowing users to influence the contents of the filter.  The API should allow you to pass the already-parsed filter object straight into client.search (removing the need to parse it a second time).

**Comment by randomsock** [comment]
Awesome, yep parsing first and then passing the Filter tree to `search()` works a treat.

One non-urgent niggle for next time your in there: the [errors](http://ldapjs.org/errors.html) doc says:

> All errors in the ldapjs framework extend from an abstract error type called `LDAPError`.

but `parseFilter()` just throws a basic `Error`.  I've wrapped that in your `LDAPError` for now so I can handle it appropriately downstream.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
