### ISSUE TITLE
ldapjs throws an exception and refuses further connection

### ISSUE THREAD

**Issue by coccusca** [mcavage/node-ldapjs#285]
Every a few days, ldapjs throws an exception as follows:
ConnectionError: 1__ldap://xx.xx.xx.xx:389 closed
    at /usr/share/node/node_modules/ldapjs/lib/client/client.js:127:15
    at Array.forEach (native)
    at Socket.onClose (/usr/share/node/node_modules/ldapjs/lib/client/client.js:124:39)
    at Socket.emit (events.js:107:17)
    at TCP.close (net.js:485:12)

and refuses any further connection
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at Socket.Writable.write (_stream_writable.js:214:5)
    at Socket.write (net.js:634:40)
    at Client._send (/usr/share/node/node_modules/ldapjs/lib/client/client.js:91
4:17)
    at Client.bind (/usr/share/node/node_modules/ldapjs/lib/client/client.js:367
:15)
    at WebSocket.<anonymous> (/usr/share/node/node_modules/wsProject/wss2.js:39:
17)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (/usr/share/node/node_modules/ws/lib/WebSocket.js:798:10)
    at /usr/share/node/node_modules/ws/lib/Receiver.js:473:18
    at Receiver.applyExtensions (/usr/share/node/node_modules/ws/lib/Receiver.js
:360:5)

I have to restart the program, and everything seems return to normal until next break down.

**Comment by pfmooney** [comment]
It would not surprise me if the remote server is timing out your connection (due to inactivity or a different limit).  If you have not configured the client to perform a reconnect in the face of such events, then any further LDAP methods called on the client will fail due to an absent connection.

I would recommend looking into those topics.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
