### ISSUE TITLE
how to use TLS in this module

### ISSUE THREAD

**Issue by xianfeng95** [mcavage/node-ldapjs#322]
var ldapjs = require("ldapjs");
var ldapUrl='ldaps://lunar:636';
var client = ldapjs.createClient({
        url: ldapUrl
    });
but this thow err:
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)

**Comment by aneelaSaleem** [comment]
Please look at issue #307
It might help you solve the problem

**Comment by pfmooney** [comment]
It appears that the certificate of the server you're connecting to is not signed by a CA your system trusts. (Or lacks an appropriate cert chain.)  Please confirm that the server SSL is configured properly and/or specify the necessary TLS options to extend your trust to the server.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
