### ISSUE TITLE
Writing to binary attributes

### ISSUE THREAD

**Issue by samloh84** [mcavage/node-ldapjs#325]
I would like to update a binary attribute jpegPhoto in user entries on a OpenLDAP server.
```javascript
var change = new ldap.Change({
    operation: 'replace',
    modification: {
        'jpegPhoto;binary': photo // photo is a Buffer object
    }
});

client.bind('cn=admin,dc=example,dc=com', 'secret', function (err) {
    if (err) {
        throw err;
    }
    client.modify('ou=users,dc=example,dc=com', change, function (err) {
        if (err) {
            throw err;
        }
    });
});
```

I am currently getting this error:
```
UndefinedAttributeTypeError: jpegPhoto;binary: option "binary" not supported with type
    at messageCallback (/home/developer/ldapClient/node_modules/ldapjs/lib/client/client.js:1419:45)
    at Parser.onMessage (/home/developer/ldapClient/node_modules/ldapjs/lib/client/client.js:1089:14)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser.write (/home/developer/ldapClient/node_modules/ldapjs/lib/messages/parser.js:117:8)
    at Socket.onData (/home/developer/ldapClient/node_modules/ldapjs/lib/client/client.js:1076:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

Is writing binary attributes currently supported?

**Comment by pfmooney** [comment]
That appears to be an error emitted by the server.  Have you attempted the replace operation without the `;binary` suffix? (While still providing the buffer of binary data?

**Comment by augcampos** [comment]
I I want to make e add with a binary field how do I set it on the entry?

var entry = { uid: 'lalala', jpegPhoto: '{{ img in BASE64 }}'
ldap_client.add(dn, entry,function (err) {
...
});

**Comment by pfmooney** [comment]
@augcampos You'll want to use a Buffer object with the raw binary data instead of base64 encoding it.

**Comment by augcampos** [comment]
I there thanks for the reply.
I already try
var imgBase64 = '/9kljnfkjsdnf.......==';
.......
var userPhoto = new Buffer(imgBase64);
also try 
var userPhoto = new Buffer(imgBase64, 'base64');
also try 
var userPhoto = new Buffer(imgBase64, 'binary');
.....
var entry = { uid: 'lalala', jpegPhoto: userPhoto };
ldap_client.add(dn, entry,function (err) {
...
});

all did not work :(

PS: What I need is to add a new entry on ldap with the jpegPhoto filled with a image-src 
like ''' <img ng-src="{{'data:image/png;base64,'+main.user.jpegPhoto}}" > '''  from a LDAP jpegPhoto property

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
