### ISSUE TITLE
Client#search unhandled exception for malformed search filter

### ISSUE THREAD

**Issue by nazrhyn** [mcavage/node-ldapjs#327]
When `Client#search` is called with a malformed search filter, the error is not returned to the callback. Here's an example stack trace starting at `search`:

```
Error: (userPrincipalName=user@company.com has unbalanced parentheses
    at matchParens (.../node_modules/ldap-filter/lib/index.js:49:11)
    at _buildFilterTree (.../node_modules/ldap-filter/lib/index.js:155:18)
    at _parseString (.../node_modules/ldap-filter/lib/index.js:411:17)
    at Object.module.exports.parse (.../node_modules/ldap-filter/lib/index.js:422:12)
    at Object.parseString (.../node_modules/ldapjs/lib/filters/index.js:176:25)
    at Client.search (.../node_modules/ldapjs/lib/client/client.js:769:30)
```

I noticed this due to our use of **[vesse/passport-ldapauth](https://github.com/vesse/passport-ldapauth)** which uses **[vesse/node-ldapauth-fork](https://github.com/vesse/node-ldapauth-fork)** which uses **ldapjs**. The 1.0.0 version of **ldapjs** fixed some of the other uncaught exceptions we had been seeing, so thanks for that. Looks like there are just still a few left that are slipping through the cracks.

**Comment by pfmooney** [comment]
That is indeed a malformed filter.  Such exceptions are considered programmer error (not adequately cleansing input) and are emitted as such.  Please see that the module using ldapjs provides a valid filter and/or that the input passed to it is valid.
