### ISSUE TITLE
getting events.js:141 error

### ISSUE THREAD

**Issue by jbnhf23** [mcavage/node-ldapjs#337]
I follow this guide http://ldapjs.org/guide.html#add but get an error without any description or anything. My bash only prints "events.js:141"

Could it be an issue with node 5.4.0 and ldapjs?

I am testing the server using openLDAP with this command:
ldapadd -H ldap://myIP:1389 -x -D cn=root -w secret -f ~/Documents/add-this-user.ldif

And add-this-user.ldif contains:
dn: cn=myUserName,ou=users,o=myhost
objectClass: unixUser
cn: myUserName
uid: 1003
gid: 3000
homeDirectory: c:/myUserName
shell: c:/myUserName.cmd

**Comment by pfmooney** [comment]
Without a more detailed stack trace, it's difficult to determine what the problem may be.

**Comment by jbnhf23** [comment]
Can I do anything to get a more detailed stacktrace?

**Comment by jbnhf23** [comment]
Have anyone else a working example using node 5.4 and ldapjs?

This morning I was also testing the server.modify(..) code from the guide above.

I test it with OpenLDAP using this command:
ldapmodify -H ldap://localhost:1389 -x -D cn=root -w secret -f modify-this.ldif

I got the following errors, maybe that can give a hint:
web.1  | {"name":"ldapjs","component":"client","hostname":"myhostname","pid":1740,"level":50,"msg":"127.0.0.1:56141::2 uncaught exception: Error: write EPIPE\n    
at exports._errnoException (util.js:856:11)\n    
at Socket._writeGeneric (net.js:675:26)\n    
at Socket._write (net.js:694:8)\n    
at doWrite (_stream_writable.js:292:12)\n    
at writeOrBuffer (_stream_writable.js:278:5)\n    
at Socket.Writable.write (_stream_writable.js:207:11)\n    
at Socket.write (net.js:618:40)\n    
at Socket.Writable.end (_stream_writable.js:433:10)\n    
at Socket.end (net.js:400:31)\n    
at Server.<anonymous> (C:\\baldur-ldp\\app.js:300:16)","time":"2016-01-12T14:18:27.926Z","v":0}
web.1  | events.js:141

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
