### ISSUE TITLE
Problem using LDAP with StartSSL

### ISSUE THREAD

**Issue by tuudik** [mcavage/node-ldapjs#339]
Hi!
Trying to configure Rocket.Chat to authenticate with LDAP using StartTLS. But unfortunately I get error.
```
Exception while invoking method 'login' TypeError: Object [object global] has no method '_send'
    at starttls (/usr/share/Rocket.Chat/programs/server/npm/rocketchat_ldap/node_modules/ldapjs/lib/client/client.js:955:15)
    at packages/meteor/helpers.js:118:1
    at startTLS (packages/rocketchat_ldap/ldap_server.js:58:1)
    at [object Object].LDAP.ldapCheck (packages/rocketchat_ldap/ldap_server.js:94:1)
    at [object Object].__coffeescriptShare (packages/rocketchat_ldap/ldap_server.js:256:1)
    at accounts_server.js:462:32
    at tryLoginMethod (accounts_server.js:239:14)
    at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
    at [object Object].methods.login (accounts_server.js:522:27)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
```

Do you have any ideas, what problem  is referenced  on error ```Exception while invoking method 'login' TypeError: Object [object global] has no method '_send' at starttls```?

From slapd log i can see that it's trying to connect but:
```
Jan 20 10:55:26 ldap slapd[13534]: conn=2157 fd=13 ACCEPT from IP=127.0.0.1:38059 (IP=0.0.0.0:110)
Jan 20 10:55:26 ldap slapd[13534]: conn=2157 fd=13 closed (connection lost)
```

I used custom port 110 (redirected to 365), I tried with LDAP:// and LDAPS://. Also tried with "Reject Unauthorized cert" true and false, issue remains. CA cert that I used, was the one that was used to generate cert for openldap.

**Comment by pfmooney** [comment]
It would appear that some of the Meteor stuff you're using is rebinding that function.  I don't believe that any of the public client methods support being bound to anything but the client object itself.

**Comment by tuudik** [comment]
Thank you!

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
