### ISSUE TITLE
New User Not Enabled Upon Creation

### ISSUE THREAD

**Issue by jasoncmcg** [mcavage/node-ldapjs#342]
When I create a new user in *Active Directiory*, it is _disabled_ until I **manually** reset the password and enable them (using ADUC).

I am using the following approach:
```
  client.add ( userDn, entry, function (err, result) { console.log(err, result); }  } );
```

With the following entry object:

```
    var entry = {
	displayName: displayName, 	
	sAMAccountName: samAccountName, 	
	name: name,
	sn: name,
	givenName: givenName,
	mailNickname: samAccountName,
	userPrincipalName: userPrincipalName, 
	physicalDeliveryOfficeName: officeName, 	
	company: company, 	
	info: sourceInfo, 	
	department: locationCode, 	
	mail: [email],
	objectClass: ['organizationalPerson', 'person', 'top', 'user'],
	objectCategory: personCategory
	description: 'auto created on ' + (new Date()).toLocaleString()
  }
```

If I attempt to add in the `userPassword` property, the process will return a [UnwillingToPerformError] with a 5003 WILL_NOT_PERFORM code. 

I have tried to use the iconv-lite library to encode in utf16-le and I have tried the node-ssha256 found in the only references that I could dig up.

According to this powershell reference, the account is disabled because I am not able to supply the proper secureString password with the account:

```
   -AccountPassword SecureString
       A new password value for an account.
       This value is stored as an encrypted string.
       If an empty or $null password is specified a Random password will be set.
       If the password does not meet password policy the account will be disabled
        
       User accounts, by default, are created without a password.
       A valid user account password may also be specified manually.
       User accounts will never be enabled unless a valid password is set
                
       The following example will prompt for a password.
          -AccountPassword (Read-Host -AsSecureString "AccountPassword")
```

Adding a `userAccountControl: 512` to the object to enable the account upon creation also fails. 

Calling a modify from the creation callback also fails. And, this is using a password that is compliant with the enforced policies.

**Comment by jasoncmcg** [comment]
I also tried adapting this response in forming the string:
http://www.dirmgr.com/blog/2010/8/26/ldap-password-changes-in-active-directory.html

> Unfortunately, Active Directory is extremely bad at telling you what's wrong and "problem 5003". Are you sure you're connecting over SSL? Are you sure that the password you're sending is surrounded by quotation marks? Are you sure it is encoded using UTF-16 with a little endian ordering (which is an extremely unusual encoding)? Are you sure that the password is complex enough to satisfy Active Directory's strength requirements (e.g., it's long enough and has a mix of uppercase and lowercase characters, digits, and symbols)?

Another example of using utf16le
https://snipt.net/Fotinakis/change-active-directory-password-via-ldap-modify-call/

```
# NOTE: The article says to BER encode the password octet stream before
# sending for change, but doing so causes the server to give its standard
# "will not perform" error on password change. So, no BER encoding is done here.
username = 'someUser'
new_pass = 'ne$wP4assw0rd3!'
new_password = ('"%s"' % new_pass).encode("utf-16-le")
```

**Comment by jasoncmcg** [comment]
nvm, I believe it to be related to the ldaps connection with a cerificate.

**Comment by miqueloc** [comment]
I have the same issue. Trying to enable a user brings me an error: WILL_NOT_PERFORM
This makes ldapjs useless as I can't use users that are disabled.
Is there any workaround to enable a user if 'userAccountControl': 66048. 512, etc. doesn't work?

The only way I can enable a user is by disabling the password.
``` 
{ UnwillingToPerformError: 0000052D: SvcErr: DSID-031A12D2, problem 5003 (WILL_NOT_PERFORM), data 0

    at messageCallback (C:\Users\miguel.olivares\Documents\tests\storeUITest\node_modules\ldapjs\lib\client\client.js:1419:45)
    at Parser.onMessage (C:\Users\miguel.olivares\Documents\tests\storeUITest\node_modules\ldapjs\lib\client\client.js:1089:14)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.write (C:\Users\miguel.olivares\Documents\tests\storeUITest\node_modules\ldapjs\lib\messages\parser.js:111:8)
    at Socket.onData (C:\Users\miguel.olivares\Documents\tests\storeUITest\node_modules\ldapjs\lib\client\client.js:1076:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
  lde_message: '0000052D: SvcErr: DSID-031A12D2, problem 5003 (WILL_NOT_PERFORM), data 0\n\u0000',
  lde_dn: null }
```

**Comment by dthree** [comment]
There's not a way around this, really. You need to use `ldaps`, which means you have to set your DC up as a cert authority.

**Comment by 360noscope** [comment]
my AD is already CA and got ldaps and i can't still add user and enabled it :(

**Comment by djolson11** [comment]
I know this is old, but I was able to get a user created and enabled by passing

userAccountControl: "512" 

as a property.

**Comment by kdi-1** [comment]
Link with values for userAccountControl.
https://jackstromberg.com/2013/01/useraccountcontrol-attributeflag-values/
You can combine them so 
userAccountControl : "66048" = 65536 (DONT_EXPIRE_PASSWORD) + 512 (NORMAL_ACCOUNT)

**Comment by guenthergmbh** [comment]
As it was mentioned, first of all you need to make sure that your Domain Controller accepts connections via `ldaps`. Otherwise you are not able to store or change passwords at all. Secondly the passwords are stored in the field `unicodePwd` and need to be encoded. I am doing that as follows:

```
encodePassword(password) {
   let newPassword = '';
   password = "\"" + password + "\"";
   for (let i = 0; i < password.length; i++) {
      newPassword += String.fromCharCode(password.charCodeAt(i) & 0xFF,(password.charCodeAt(i) >>> 8) & 0xFF);
   }
   return newPassword;
}
```

So my entry object looks like:
```
distinguishedName: `cn=${this.user.username},ou=mytestou,dc=mydomain,dc=com`,
cn: this.user.username,
givenName: this.user.givenName,
sn: this.user.surname,
displayName: `${this.user.surname}, ${this.user.givenName}`,
mail: `${this.user.username}@mydomain.com`,
uid: this.user.username,
userPrincipalName: `${this.user.username}@mydomain.com`,
sAMAccountName: this.user.username,
objectClass: ['top', 'person', 'organizationalPerson', 'user'],
userAccountControl:'512',
unicodePwd: this.encodePassword(this.user.password)
```
Hope this helps.

Site note:
You should not install your certificate authority on your DC. Just get an independent server for that.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
