### ISSUE TITLE
client.starttls fails with Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by litewhatever** [mcavage/node-ldapjs#349]
Hello

Our LDAP server has been configured with a certificate which has been issued by our own CA (e.g it is self-signed and untrusted by node).
We can use ldapjs with ldaps:// if we specify CA certificate but there seems to be an issue when using starttls even if we specify CA certificate.

Please take a look at the following code (it isn't beautiful but should do the job):

```
var assert = require('assert');
var ldap = require('ldapjs');
var fs = require('fs');

function authDN(dn, password, cb) {
  var client = ldap.createClient({ url: 'ldap://some.host.net:110' });

  client.bind(dn, password, function (err) {
    //client.unbind();
    cb(err === null, err);
  });

  var opts = {
//    'host' : 'some.host.net',
    'rejectUnauthorized' : true,
    'ca' : [fs.readFileSync('ca_server.pem')]
  }

  client.starttls(opts, null, function(err, res) {
    assert.ifError(err);
    client.unbind();
  // Client communication now TLS protected
  });

}

function output(res, err) {
  if (res) {
    console.log('success');
  } else {
    console.log('failure');
  }
}

// should print "success"
authDN('cn=operator,dc=ldap,dc=host,dc=net', 'password', output);
```

This will fail with the following message:

```
assert.js:326
assert.ifError = function(err) { if (err) {throw err;}};
                                                 ^
Error: Hostname/IP doesn't match certificate's altnames
    at SecurePair.<anonymous> (tls.js:1390:23)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at Socket.ondata (stream.js:51:26)
```

If I remove comment from opts e.g `'host' : 'some.host.net'` the connection will succeed.

I'm not a programmer but it looks to me as tls.connect can't be used this way as the hostname should be specified.

From documentation:
https://nodejs.org/api/tls.html#tls_tls_connect_options_callback
> Creates a new client connection to the given port and host (old API) or options.port and options.host. (If host is omitted, it defaults to localhost.) options should be an object which specifies:
...

**Comment by pfmooney** [comment]
The situation is complicated, in the case of starttls, by the fact an existing socket is being "upgraded" to TLS.  May I inquire about the version of node.js you used to test in this case?  Automatic population of the TLS hostname does appear to be present in some (but not all) versions.

**Comment by litewhatever** [comment]
```
$ node -v
v0.10.40
```

**Comment by litewhatever** [comment]
Yes, this seems to be true. Did some quick testing with node 5.6.0 - works fine.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
