### ISSUE TITLE
TypeError returned when i can modify 

### ISSUE THREAD

**Issue by Oladapo** [mcavage/node-ldapjs#355]
Hi, a really weird error occurs when i call modify on the client object. Here's the stack trace:

assert.ifError = function(err) { if (err) throw err; };
                                          ^

TypeError: this._modification.toBer is not a function
    at Change.toBer (/home/dani/Dev/project/node_modules/ldapjs/lib/change.js:204:28)
    at /home/dani/Dev/project/node_modules/ldapjs/lib/messages/modify_request.js:80:7
    at Array.forEach (native)
    at ModifyRequest._toBer (/home/dani/Dev/project/node_modules/ldapjs/lib/messages/modify_request.js:79:16)
    at ModifyRequest.LDAPMessage.toBer (/home/dani/Dev/project/node_modules/ldapjs/lib/messages/message.js:95:19)
    at Client._sendSocket (/home/dani/Dev/project/node_modules/ldapjs/lib/client/client.js:1476:31)
    at Client._send (/home/dani/Dev/project/node_modules/ldapjs/lib/client/client.js:1363:17)
    at Client.modify (/home/dani/Dev/project/node_modules/ldapjs/lib/client/client.js:672:15)
    at /home/dani/Dev/project/lib/ldap-util.js:106:15
    at sendResult (/home/dani/Dev/project/node_modules/ldapjs/lib/client/client.js:1395:12)

Any thoughts?

**Comment by Oladapo** [comment]
P.s I am querying against openldap verison 2.4.31. If it helps

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
