### ISSUE TITLE
Running expressjs app using ldapjs results in strict mode error

### ISSUE THREAD

**Issue by jaxley** [mcavage/node-ldapjs#390]
We run our apps with the --use_strict global flag and this blows up 

```
node_modules/ldapjs/node_modules/assert-plus/assert.js:41
                stackFunc = stackFunc || _assert.caller;
                                                ^

TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
    at _assert (/Users/foo/MyApp/node_modules/ldapjs/node_modules/assert-plus/assert.js:41:49)
    at Object.object (/Users/foo/MyApp/node_modules/ldapjs/node_modules/assert-plus/assert.js:141:9)
    at new MessageTracker (/Users/foo/MyApp/node_modules/ldapjs/lib/client/client.js:180:10)
    at initSocket (/Users/foo/MyApp/node_modules/ldapjs/lib/client/client.js:1059:15)
    at connectSocket (/Users/foo/MyApp/node_modules/ldapjs/lib/client/client.js:1043:5)
    at Backoff.<anonymous> (/Users/foo/MyApp/node_modules/ldapjs/lib/client/client.js:1203:5)
    at emitTwo (events.js:106:13)
    at Backoff.emit (events.js:191:7)
    at Backoff.onBackoff_ (/Users/foo/MyApp/node_modules/backoff/lib/backoff.js:53:10)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

Any chance ldapjs could be fixed to work in strict mode?

**Comment by jaxley** [comment]
The issue appears to be that ldapjs is pinned to 0.2.0 of assert-plus instead of the latest 1.0.0 where this is fixed:  https://github.com/mcavage/node-assert-plus/issues/23

Can you up-rev the module?

**Comment by pfmooney** [comment]
See bc1e3146e1cc4b871fad79d0922554aa1fab9a3a

**Comment by jaxley** [comment]
Excellent!  Thought this project was dead and gone.

Any timeframe for a new module release to npm?

**Comment by farheen14aslam** [comment]
The issue still persists since ldap-filter's version is 0.2.2 which is having a dependency on assert-plus's older version. So if we update the version of ldap-filter to 0.3.3 in package.json, the error will be resolved in ldap-filter as it has the dependency on newer assert-plus library.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
