### ISSUE TITLE
Authentication 0x8a not supported

### ISSUE THREAD

**Issue by Qix-** [mcavage/node-ldapjs#400]
Hi -

I know this is probably not a bug with ldap.js but I'm trying to figure out exactly how to debug this.

Right now we have (what I would consider to be) a legacy piece of software that we're trying to use with this library, and upon connection I get:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
VError: Parser error for <snipped IP>:53005: authentication 0x8a not supported
    at Parser.<anonymous> (/src/project/node_modules/ldapjs/lib/server.js:442:26)
    at Parser.emit (events.js:98:17)
    at Parser.write (/src/project/node_modules/ldapjs/lib/messages/parser.js:107:10)
    at Socket.<anonymous> (/src/project/node_modules/ldapjs/lib/server.js:460:16)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
```

I figured it was just some sort of authentication scheme enumeration or something that the library didn't support, but we're not sure what kind of authentication it's using or if it's some strange bug with this library.

Is there anything we can do to debug this further?

**Comment by SergeS** [comment]
@Qix- This is GSS-API authentication - it is not supported by ldapjs, so simple authentication should be used instead

**Comment by VBustamante** [comment]
Hi, sorry for reopening an old thread but I'm facing a related problem. The application I'm developing needs to interface with a GUI program that makes it pretty easy to request GSS-API authentication by mistake, which crashes the whole server. There seems to be no way to catch the Parser error caused by a bad auth attempt, and no hooks seem to be called before the server errors out. 

Am I missing something? is there a way to catch the unsupported auth exception and treat it gracefully?

**Comment by UziTech** [comment]
Can you handle it in `uncaughtException` on the server?

```js
process.on("uncaughtException", (error) => {
	// handle errors
});
```

**Comment by jsumners** [comment]
A PR that implements better error handling for unsupported authorization mechanisms would also be welcome.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
