### ISSUE TITLE
No error event when reconnect is set to true

### ISSUE THREAD

**Issue by moehlone** [mcavage/node-ldapjs#403]
Hi,

I am trying to connect the ldapjs client with our LDAP server.
When the server is not reachable/available, the correct error is thrown. 
For example:

`{ Error: connect ECONNREFUSED 127.0.0.1:389
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 389 }`

But when I set `reconnect: true`  in options, no error is thrown on initial connect and instead the application hangs up endless. Is there any way to get around this?

Best regards
Philipp

**Comment by moehlone** [comment]
The source code of the client showed, that the reconnect attribute also accepts an object as value and so you easily can do (for example) the following:

```javascript
ldap.createClient({
    "initialDelay": 100,
    "maxDelay": 500,
    "failAfter": 5
});
```

Please add the reconnect opportunity to your documentation.

**Comment by JaredBoone** [comment]
I'd like to echo the request to add the reconnect option to the documentation. This undocumented option is useful in case you need to call bind() a second time on a Client object after calling unbind().

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
