### ISSUE TITLE
LDAP client, promisified and error handling

### ISSUE THREAD

**Issue by frankbenoit** [mcavage/node-ldapjs#417]
Hi

i use code like the below. In general it works. 

    var Promise = require('bluebird');
    var client = ldap.createClient({
		  url: ldapUrl,
		  timeout: 5000,
		  connectTimeout: 10000
	});
	Promise.promisifyAll(client);
  	return = client
  		.bindAsync( username, password )
  		.then( function(){
               //...

Now, when the VPN is not available, i get an error and my application terminates. I don't know how to handle:

    events.js:160
      throw er; // Unhandled 'error' event
      ^

    Error: getaddrinfo ENOTFOUND ...:389
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

I learned that i can do:

     client.on('error', function(e){
       // ...
     });

This makes the program to no more terminate, but the returned promise is not resolved/rejected.
Can you please help?

Frank

**Comment by mjhm** [comment]
I'm doing something like this
```
 clientErrorPromise = new Promise(function(resolve, reject) {
  client.once('error', reject);
});
bindPromise = client.bindAsync(username, password);
return Promise.race(clientErrorPromise, bindPromise);
```
That seems to work for some of my errors at least.  It's a bit hacky though, and I sure wish the module had more conventional error handling.

**Comment by frankbenoit** [comment]
This works, great.
Thank you!

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
