### ISSUE TITLE
Ambiguous error -  new TypeError('controls must be [Control]');

### ISSUE THREAD

**Issue by ORESoftware** [mcavage/node-ldapjs#440]
I have this error:
```

/Users/alexamil/WebstormProjects/ldap-pool/node_modules/ldapjs/lib/client/client.js:77
    throw new TypeError('controls must be [Control]');
    ^

TypeError: controls must be [Control]
    at validateControls (/Users/alexamil/WebstormProjects/ldap-pool/node_modules/ldapjs/lib/client/client.js:77:11)
    at Client.bind (/Users/alexamil/WebstormProjects/ldap-pool/node_modules/ldapjs/lib/client/client.js:473:16)
```

Maybe a link to documentation would help? Not sure what to do with this error.

**Comment by ORESoftware** [comment]
ahh, it looks like this error appears when we call client.bind() without a callback

**Comment by riginoommen** [comment]
@ORESoftware I am also facing this issue we are using typescript.

Can you please share the fix as little elaborate

**Comment by ORESoftware** [comment]
@riginoommen I have a very successful project that I have been using at work - I'd recommend using this lib:

https://github.com/ORESoftware/ldap-pool

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
