### ISSUE TITLE
lde_message: 'dn: attribute type undefined on ldap.add()

### ISSUE THREAD

**Issue by jb181991** [mcavage/node-ldapjs#457]
Hi, I'm new to this and I'm trying to add child in the group "Investor" which is in the "arcana" organizational unit. This is my code:

`var ldap = require('ldapjs');`
`var ldap_server = ldap.createClient({url: 'ldap://192.168.1.250'});`
`ldap_server.bind('cn=admin,dc=sample,dc=com', 'p1n0yak0m3', function (err) {`
`  if (err) {`
`    console.log('LDAP binding failed... disconnecting');`
`  }else{`
`  	console.log("Bind Success");`
`  }`
`});`
`var entry = {`
`	dn: 'dc=sample, dc=com',`
`  	gidNumber: '501',`
`  	objectClass: 'posixAccount',`
`  	uidNumber: '1000',`
`  	userPassword: 'password',`
`  	homeDirectory: '/home/users/fsmith',`
`  	cn: 'fred smith',`
`  	sn: 'smith',`
`  	loginShell: '/bin/bash'`
`};`
`ldap_server.add('cn=fredsmith, cn=Investor, ou=arcana, dc=sample, dc=com', entry, function(err) {`
`	if(err)`
`	{`
`		console.log(err);`
`	}else{`
`		console.log("Success");`
`	}`
`});`

**but I don't know why is it that I have this error.**

`{ UndefinedAttributeTypeError: UndefinedAttributeTypeError
    at messageCallback (/var/www/html/arcana_thirdparty/node_modules/ldapjs/lib/client/client.js:1419:45)
    at Parser.onMessage (/var/www/html/arcana_thirdparty/node_modules/ldapjs/lib/client/client.js:1089:14)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:191:7)
    at Parser.write (/var/www/html/arcana_thirdparty/node_modules/ldapjs/lib/messages/parser.js:111:8)
    at Socket.onData (/var/www/html/arcana_thirdparty/node_modules/ldapjs/lib/client/client.js:1076:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10) lde_message: 'dn: attribute type undefined', lde_dn: null }`

**Please let me know what did I missed in my code. Thank you.**

**Comment by hatontuyen** [comment]
Hi,
You need to remove _dn: 'dc=sample, dc=com'_ from your entry because there is no dn attribute definition in your schema.

**Comment by EmilianoGaytan** [comment]
// this worked for meconfigure user
    var newDN = "cn=nguy,dc=example,dc=com";
    var newUser = {
      cn: 'new guy',
      sn: 'guy',
      uid: 'nguy',
      //mail: 'nguy@example.org',
      objectClass: 'inetOrgPerson',
      userPassword: ssha.create('s00prs3cr3+')
    };
 

    // Add user
    this._client.add(newDN, newUser, function(err,res) {
      // handle errors ( move to try catch)
      if (err) {
        console.error("user  add FAILED: %j", 'dn: ' + err.dn + '\n code: ' + err.code + '\n message: ' + err.message);
      } else {
        console.log(" user add WORKED: %j"+ res  + res.dn + '\n code: ' + res.code + '\n message: ' + res.message);
      }
    });
  

    // Close connection
    this._client.unbind(  function(err,res) {
      // handle errors ( move to try catch)
      if (err) {
        console.error(" close  connection FAILED: %j", 'dn: ' + err.dn + '\n code: ' + err.code + '\n message: ' + err.message);
      } else {
        console.log("  close connection WORKED: %j"+ res   );
      }
    });

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
