### ISSUE TITLE
JSON.stringify parse Circular

### ISSUE THREAD

**Issue by MatthiasSkopek** [mcavage/node-ldapjs#484]
I need to auth to an ldap-system, which I can not modify. 
But when I make a bind with the wrong credentials, it works but it's Invalid.

`{"dn":"","code":49,"name":"InvalidCredentialsError","message":"Invalid Credentials"}`

When I use the right credentials I get this error. Can I make the parsing myself? Or where is the Line to rewrite the paring?

`/usr/src/app/node_modules/express/lib/response.js:1119
express    |     : JSON.stringify(value);
express    |            ^
express    | 
express    | TypeError: Converting circular structure to JSON
express    |     at JSON.stringify (<anonymous>)
express    |     at stringify (/usr/src/app/node_modules/express/lib/response.js:1119:12)
express    |     at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:260:14)
express    |     at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:158:21)
express    |     at /usr/src/app/routes/users.js:56:17
express    |     at sendResult (/usr/src/app/node_modules/ldapjs/lib/client/client.js:1395:12)
express    |     at messageCallback (/usr/src/app/node_modules/ldapjs/lib/client/client.js:1421:16)
express    |     at Parser.onMessage (/usr/src/app/node_modules/ldapjs/lib/client/client.js:1089:14)
express    |     at emitOne (events.js:116:13)
express    |     at Parser.emit (events.js:211:7)
`

Thanks in advance.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
